version: '3.8'

services:
  web:
    restart: always
    build: .
    command: uvicorn main:app --host 0.0.0.0 --reload
    volumes:
      - .:/app
    ports:
      - 8000:8000
    environment:
      - DATABASE_URL=postgresql://${DB_USER}:${PASSWORD}@${HOST}/${DATABASE}
    depends_on:
      - db

  db:
    image: postgres:13-alpine
    volumes:
      - postgres_data:/var/lib/postgresql/data/
    expose:
      - 5432
    environment:
      - POSTGRES_USER=${DB_USER}
      - POSTGRES_PASSWORD=${PASSWORD}
      - POSTGRES_DB=${DATABASE}
      - POSTGRES_HOST=${HOST}

    env_file: .env

volumes:
  postgres_data:
    
    
